### ISSUE TITLE
Site doesnt work correctly

### ISSUE THREAD

**Issue by CrazyEgor14** [Deathlaide/artPortfolio#1]
Pressing button "Various games"(https://deathlaide.github.io/artPortfolio/games.html) after already going to this page cause error bcause of invalid address (https://deathlaide.github.io/artPortfolio/Various%20games.html).
![image](https://user-images.githubusercontent.com/102807309/195618775-43c631e0-4347-4c4a-a9ba-e26ba8de8687.png)

**Comment by Deathlaide** [comment]
Fixed it, thanks
